name: JoinTitle
main: JoinTitle\Main
version: 1.0.0
api: [3.0.0]
load: POSTWORLD
author: NickTehUnicorn
description: A plugin that sends title to player on join.

commands:
  jointitle:
    desciption: Configure JoinTitle.
    permission: op
